### ISSUE TITLE
How can I see the job output (stdout/stderr)?

### ISSUE THREAD

**Issue by pqvst** [blacklabelops/jobber-cron#26]
I can't seem to find any documentation regarding how I can see my job's output. All I see is `exit status`. Any advice would be appreciated.

**Comment by pqvst** [comment]
Ok, so it seems that jobber doesn't do anything with stdout/stderr for jobs, but I couldn't find any documentation for this. For anyone else who is wondering, the best way I found was to pipe the job output to a file, and then mount that file (or directory) on the host. For example:

```yaml
version: '3'

services:

  my-job:
    image: blacklabelops/jobber
    volumes:
      - ./logs:/logs
    environment:
      - JOB_NAME1=my-job
      - JOB_COMMAND1=foobar > /logs/output.txt 2>&1
      - JOB_TIME1=1
```
